package com.polio.poliokeycloak;

import com.polio.poliokeycloak.keycloak.service.KeycloakPermissionService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpMethod;

@SpringBootTest
class PolioKeycloakApplicationTests {

    @Autowired
    KeycloakPermissionService keycloakPermissionService;
    @Test
    void contextLoads() {
        //String accessToken =  "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJVR3pubEo0NlNmLUhOTno0M1NYcHNPOTQ1aFQ3amxBSEdTTDhuRnVmamEwIn0.eyJleHAiOjE3NDkyMTY5NjcsImlhdCI6MTc0OTIxNjY2NywianRpIjoiNzFkOGQwYWYtZTkwMi00YmJhLWFlY2YtOWZiZjhkN2Q2ZWM5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg5L3JlYWxtcy9wb2xpbyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI1YWFjOGY1Yy0yZWZmLTQ2ZmMtODNhZS0xNmVlYWQ3OTNlYTciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJwb2xpby10b3ktY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6ImE3NjIwMjRlLTVjMTEtNDUzZi04ZDNkLTg4M2YxNDgzZDAyNSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1wb2xpbyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InBvbGlvLXRveS1jbGllbnQiOnsicm9sZXMiOlsiU2FtcGxlLVJvbGUiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6ImE3NjIwMjRlLTVjMTEtNDUzZi04ZDNkLTg4M2YxNDgzZDAyNSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiZmlyc3QgbGFzdCIsInByZWZlcnJlZF91c2VybmFtZSI6InBvbGlvLXRveS1jbGllbnQtdXNlcjEiLCJnaXZlbl9uYW1lIjoiZmlyc3QiLCJmYW1pbHlfbmFtZSI6Imxhc3QifQ.ar99wBik5s3M6GaWESem9CnpWDl9sRDPRGE5-LjnZ_p9ti_E3FWPrT2W9mIyEnvF9dp7GjX9HPSVB5JIS3Hu7MJCETD7irLjp_rX2BjxuvnUeLOAQG60bx-jaUlcNauy-p6DMYZ6eUzwPuZEC67YrOyNL6r5h97vJbiXT58cMt1J5em7G19wgYSBVEKMbCY7veeH4JDRB3jGfg13Ll1u_VnN-UfP0YzcCMfiLPDhoM9keJ2TNXuhulfZiGr-UB-WE-5XfgZVfrvHgHcK2wPohzk5Hq0B5gOiADZ1NmipUsrcDzucRa0f0SiNV6s7xsLHTFmPvKbHzj8rLakiPKoPpg";

        //keycloakPermissionService.requestUmaTicket(accessToken,"/sample/api", HttpMethod.GET);
    }

}
