### Keycloak Direct Access Token 요청
POST http://localhost:8089/realms/polio/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=polio-toy-client&
client_secret=I6uiQiYIegQVvvIsAgFUpexpgNjfR86H&
username=polio-toy-client-user1&
password=polio-toy-client-user1


> {% client.global.set("user_access_token", response.body.access_token) %}